/**
 * Professional PDF Generation Service
 * Provides consistent, high-quality PDF exports across the application
 */

class PDFService {
  constructor() {
    this.brandColors = {
      primary: [25, 118, 210], // #1976d2
      secondary: [100, 100, 100], // Gray
      success: [46, 125, 50], // Green
      warning: [237, 108, 2], // Orange
      error: [211, 47, 47], // Red
      light: [245, 245, 245], // Light gray
      border: [200, 200, 200] // Border gray
    };
  }

  /**
   * Creates a professional PDF with table data
   * @param {Object} options - Configuration options
   * @returns {Promise<boolean>} - Success status
   */
  async createProfessionalPDF(options) {
    try {
      const {
        title,
        data,
        columns,
        filters = {},
        orientation = 'landscape',
        filename,
        additionalInfo = {}
      } = options;

      // Dynamic import for jsPDF
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF(
        orientation === 'landscape' ? 'l' : 'p', 
        'mm', 
        'a4'
      );

      let startY = this.addHeader(doc, title, filters, additionalInfo);
      
      if (data.length === 0) {
        this.addEmptyState(doc, startY);
      } else {
        this.addProfessionalTable(doc, data, columns, startY);
      }

      // Save the PDF
      const sanitizedFilename = this.sanitizeFilename(filename);
      doc.save(sanitizedFilename);
      
      return true;
    } catch (error) {
      console.error('PDF generation failed:', error);
      return false;
    }
  }

  /**
   * Adds professional header to PDF
   */
  addHeader(doc, title, filters, additionalInfo) {
    
    // Title
    doc.setFontSize(20);
    doc.setTextColor(...this.brandColors.primary);
    doc.text(title, 20, 25);

    // Date and additional info
    doc.setFontSize(10);
    doc.setTextColor(...this.brandColors.secondary);
    let yPos = 35;
    
    doc.text(`Generated on: ${new Date().toLocaleDateString('en-GB')} at ${new Date().toLocaleTimeString('en-GB')}`, 20, yPos);
    yPos += 6;

    // Company info if available
    if (additionalInfo.company) {
      doc.text(`Company: ${additionalInfo.company}`, 20, yPos);
      yPos += 6;
    }

    // Generated by info if available
    if (additionalInfo.generatedBy) {
      doc.text(`Generated by: ${additionalInfo.generatedBy}`, 20, yPos);
      yPos += 6;
    }

    yPos += 5;

    // Filters section
    if (Object.keys(filters).length > 0) {
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      
      const filterTexts = [];
      Object.entries(filters).forEach(([key, value]) => {
        if (value) {
          filterTexts.push(`${key}: ${value}`);
        }
      });
      
      if (filterTexts.length > 0) {
        doc.text(`Applied Filters: ${filterTexts.join(', ')}`, 20, yPos);
        yPos += 10;
      }
    }

    // Data count
    if (additionalInfo.totalCount !== undefined) {
      doc.setFontSize(10);
      doc.setTextColor(...this.brandColors.secondary);
      doc.text(`Total Records: ${additionalInfo.totalCount}`, 20, yPos);
      yPos += 15;
    } else {
      yPos += 10;
    }

    return yPos;
  }

  /**
   * Adds professional table with proper formatting
   */
  addProfessionalTable(doc, data, columns, startY) {
    const tableWidth = doc.internal.pageSize.width - 40; // 20mm margins on each side
    const columnWidths = this.calculateColumnWidths(columns, tableWidth);
    const rowHeight = 8;

    let yPos = startY;

    // Draw table headers
    this.drawTableHeader(doc, columns, columnWidths, yPos, rowHeight);
    yPos += rowHeight;

    // Draw table rows
    data.forEach((row, rowIndex) => {
      // Check for page break
      if (yPos > doc.internal.pageSize.height - 30) {
        doc.addPage();
        yPos = 20;
        // Redraw headers on new page
        this.drawTableHeader(doc, columns, columnWidths, yPos, rowHeight);
        yPos += rowHeight;
      }

      // Alternate row colors
      if (rowIndex % 2 === 1) {
        doc.setFillColor(...this.brandColors.light);
        doc.rect(20, yPos, tableWidth, rowHeight, 'F');
      }

      // Draw row data
      this.drawTableRow(doc, row, columns, columnWidths, yPos, rowHeight);
      yPos += rowHeight;
    });

    // Draw table borders
    this.drawTableBorders(doc, columns, columnWidths, startY, yPos, rowHeight);
  }

  /**
   * Draws table header with branding
   */
  drawTableHeader(doc, columns, columnWidths, yPos, rowHeight) {
    const tableWidth = columnWidths.reduce((sum, width) => sum + width, 0);
    
    // Header background
    doc.setFillColor(...this.brandColors.primary);
    doc.rect(20, yPos, tableWidth, rowHeight, 'F');

    // Header text
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    doc.setFont(undefined, 'bold');

    let xPos = 20;
    columns.forEach((column, index) => {
      const text = this.truncateText(column.header, columnWidths[index]);
      doc.text(text, xPos + 2, yPos + 5.5);
      xPos += columnWidths[index];
    });
  }

  /**
   * Draws table row data
   */
  drawTableRow(doc, row, columns, columnWidths, yPos, rowHeight) {
    doc.setTextColor(0, 0, 0);
    doc.setFont(undefined, 'normal');
    doc.setFontSize(8);

    let xPos = 20;
    columns.forEach((column, index) => {
      const value = this.getColumnValue(row, column);
      const displayText = this.truncateText(value, columnWidths[index]);
      
      doc.text(displayText, xPos + 2, yPos + 5.5);
      xPos += columnWidths[index];
    });
  }

  /**
   * Draws table borders
   */
  drawTableBorders(doc, columns, columnWidths, startY, endY, rowHeight) {
    doc.setDrawColor(...this.brandColors.border);
    doc.setLineWidth(0.1);

    const tableWidth = columnWidths.reduce((sum, width) => sum + width, 0);
    const tableHeight = endY - startY;

    // Vertical lines
    let xPos = 20;
    for (let i = 0; i <= columns.length; i++) {
      doc.line(xPos, startY, xPos, endY);
      if (i < columns.length) {
        xPos += columnWidths[i];
      }
    }

    // Horizontal lines
    const numberOfRows = Math.ceil(tableHeight / rowHeight);
    for (let i = 0; i <= numberOfRows; i++) {
      const lineY = Math.min(startY + (i * rowHeight), endY);
      doc.line(20, lineY, 20 + tableWidth, lineY);
    }
  }

  /**
   * Adds empty state message
   */
  addEmptyState(doc, startY) {
    doc.setFontSize(12);
    doc.setTextColor(...this.brandColors.error);
    doc.text('No data found to export.', 20, startY + 20);
  }

  /**
   * Calculates optimal column widths
   */
  calculateColumnWidths(columns, totalWidth) {
    const weights = columns.map(col => col.width || 1);
    const totalWeight = weights.reduce((sum, weight) => sum + weight, 0);
    
    return weights.map(weight => (weight / totalWeight) * totalWidth);
  }

  /**
   * Gets column value from row data
   */
  getColumnValue(row, column) {
    if (column.formatter && typeof column.formatter === 'function') {
      return column.formatter(row);
    }
    
    const value = column.key.split('.').reduce((obj, key) => obj?.[key], row);
    return value !== undefined && value !== null ? String(value) : 'N/A';
  }

  /**
   * Truncates text to fit column width
   */
  truncateText(text, maxWidth) {
    const maxLength = Math.floor(maxWidth / 2.5); // Approximate character limit
    if (text.length <= maxLength) return text;
    return text.substring(0, maxLength - 2) + '..';
  }

  /**
   * Sanitizes filename for download
   */
  sanitizeFilename(filename) {
    return filename.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  }

  /**
   * Creates employee export PDF
   */
  async exportEmployees(employees, filters = {}) {
    const columns = [
      { key: 'name', header: 'Name', width: 1.5, formatter: (emp) => `${emp.firstName} ${emp.lastName}` },
      { key: 'email', header: 'Email', width: 2 },
      { key: 'role', header: 'Role', width: 1, formatter: (emp) => (emp.role || 'user').charAt(0).toUpperCase() + (emp.role || 'user').slice(1) },
      { key: 'company', header: 'Company', width: 1.5, formatter: (emp) => emp.company || emp.originalCompanyName || '' },
      { key: 'department', header: 'Department', width: 1.5 },
      { key: 'position', header: 'Position', width: 1.5 },
      { key: 'phone', header: 'Phone', width: 1.5 },
      { key: 'joinDate', header: 'Join Date', width: 1.2, formatter: (emp) => emp.joinDate ? emp.joinDate.toLocaleDateString('en-GB') : 'N/A' },
      { key: 'isActive', header: 'Status', width: 1, formatter: (emp) => emp.isActive ? 'Active' : 'Inactive' }
    ];

    const filename = this.generateFilename('employees', filters);
    
    return this.createProfessionalPDF({
      title: 'Employee List Report',
      data: employees,
      columns,
      filters: {
        Company: filters.selectedCompany,
        Department: filters.selectedDepartment
      },
      orientation: 'landscape',
      filename,
      additionalInfo: {
        totalCount: employees.length,
        generatedBy: 'Admin Dashboard'
      }
    });
  }

  /**
   * Creates dashboard report PDF
   * @param {Object} dashboardData - Dashboard statistics and data
   * @param {Date} selectedMonth - Selected month for the report
   * @param {Object} additionalData - Additional data like company info
   * @param {Array} staffAttendanceData - Array of staff attendance records from Firebase (userName, checkInTime, checkOutTime)
   */
  async exportDashboardReport(dashboardData, selectedMonth, additionalData = {}, staffAttendanceData = []) {
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF('l', 'mm', 'a4'); // Landscape
      
      let yPos = 25;
      
      // Title
      doc.setFontSize(20);
      doc.setTextColor(...this.brandColors.primary);
      doc.text('Dashboard Report', 20, yPos);
      yPos += 15;
      
      // Date and info
      doc.setFontSize(10);
      doc.setTextColor(...this.brandColors.secondary);
      doc.text(`Generated on: ${new Date().toLocaleDateString('en-GB')} at ${new Date().toLocaleTimeString('en-GB')}`, 20, yPos);
      yPos += 6;
      
      if (additionalData.company) {
        doc.text(`Company: ${additionalData.company}`, 20, yPos);
        yPos += 6;
      }
      
      if (additionalData.generatedBy) {
        doc.text(`Generated by: ${additionalData.generatedBy}`, 20, yPos);
        yPos += 6;
      }
      
      const monthText = selectedMonth ? 
        selectedMonth.toLocaleDateString('en-GB', { month: 'long', year: 'numeric' }) : 
        'Current Month';
      doc.text(`Report Period: ${monthText}`, 20, yPos);
      yPos += 15;

      // Staff Attendance Details Section
      if (staffAttendanceData.length > 0) {
        // Check for page break
        if (yPos > doc.internal.pageSize.height - 80) {
          doc.addPage();
          yPos = 20;
        }
        
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text('Staff Check-in/Check-out Details', 20, yPos);
        yPos += 10;
        
        const staffColumns = [
          { key: 'userName', header: 'Staff Name', width: 2.2 },
          { key: 'date', header: 'Date', width: 1.3, formatter: (record) => {
            if (record.checkInTime) {
              return new Date(record.checkInTime.toDate()).toLocaleDateString('en-GB');
            }
            return record.dateString ? new Date(record.dateString).toLocaleDateString('en-GB') : 'N/A';
          }},
          { key: 'checkInTime', header: 'Check In', width: 1.5, formatter: (record) => {
            if (record.checkInTime) {
              return new Date(record.checkInTime.toDate()).toLocaleTimeString('en-GB', {
                hour: '2-digit',
                minute: '2-digit'
              });
            }
            return 'Not recorded';
          }},
          { key: 'checkOutTime', header: 'Check Out', width: 1.5, formatter: (record) => {
            if (record.checkOutTime) {
              return new Date(record.checkOutTime.toDate()).toLocaleTimeString('en-GB', {
                hour: '2-digit',
                minute: '2-digit'
              });
            }
            return 'Not recorded';
          }},
          { key: 'workingHours', header: 'Working Time', width: 1.5, formatter: (record) => {
            if (record.checkInTime && record.checkOutTime) {
              const checkIn = new Date(record.checkInTime.toDate());
              const checkOut = new Date(record.checkOutTime.toDate());
              const diffMs = checkOut - checkIn;
              const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
              const diffMinutes = Math.floor((diffMs % (1000 * 60 * 60)) / (1000 * 60));
              return `${diffHours}h ${diffMinutes}m`;
            }
            return 'N/A';
          }}
        ];
        
        this.addProfessionalTable(doc, staffAttendanceData, staffColumns, yPos);
      } else {
        // Check for page break
        if (yPos > doc.internal.pageSize.height - 40) {
          doc.addPage();
          yPos = 20;
        }
        
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text('Staff Check-in/Check-out Details', 20, yPos);
        yPos += 10;
        
        doc.setFontSize(12);
        doc.setTextColor(...this.brandColors.error);
        doc.text('No staff attendance details available for the selected period.', 20, yPos);
      }
      
      // Save the PDF
      const filename = this.generateFilename('attendance_report', { selectedMonth });
      doc.save(filename);
      
      return true;
    } catch (error) {
      console.error('Dashboard PDF generation failed:', error);
      return false;
    }
  }

  /**
   * Creates payslip PDF export - matches the payslip sample format
   */
  async exportPayslip(payslip) {
    try {
      // Dynamic imports
      const { jsPDF } = await import('jspdf');
      const { collection, getDocs, query, where } = await import('firebase/firestore');
      const { db } = await import('../services/firebase');

      const doc = new jsPDF('p', 'mm', 'a4');
      doc.setFont('helvetica');

      // Load employee and company data
      let employeeData = null;
      let companyData = null;

      try {
        // Load employee data
        const usersQuery = query(collection(db, 'users'), where('__name__', '==', payslip.employeeId));
        const usersSnapshot = await getDocs(usersQuery);
        if (!usersSnapshot.empty) {
          employeeData = usersSnapshot.docs[0].data();
        }

        // Load company data
        const companiesQuery = query(collection(db, 'companies'));
        const companiesSnapshot = await getDocs(companiesQuery);
        const companies = companiesSnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));

        // Get employee's company name (prioritize originalCompanyName)
        const employeeCompany = employeeData ?
          (employeeData.originalCompanyName || employeeData.company) : null;

        console.log('📊 Payslip Company Matching:');
        console.log('- Employee ID:', payslip.employeeId);
        console.log('- Employee Data:', employeeData ? 'Found' : 'Not Found');
        console.log('- Employee Company:', employeeCompany);
        console.log('- Employee originalCompanyName:', employeeData?.originalCompanyName);
        console.log('- Employee company:', employeeData?.company);
        console.log('- Payslip Company:', payslip.company);
        console.log('- Available Companies:', companies.map(c => c.name));

        // Try to find company with multiple matching strategies
        if (employeeCompany) {
          // Strategy 1: Exact match (case-insensitive, trimmed)
          const normalizedEmployeeCompany = employeeCompany.trim().toLowerCase();
          companyData = companies.find(c =>
            c.name?.trim().toLowerCase() === normalizedEmployeeCompany
          );

          console.log('- Match Strategy 1 (exact):', companyData ? `Found: ${companyData.name}` : 'Not found');

          // Strategy 2: Partial match (if exact fails)
          if (!companyData) {
            companyData = companies.find(c =>
              c.name?.trim().toLowerCase().includes(normalizedEmployeeCompany) ||
              normalizedEmployeeCompany.includes(c.name?.trim().toLowerCase())
            );
            console.log('- Match Strategy 2 (partial):', companyData ? `Found: ${companyData.name}` : 'Not found');
          }
        }

        // Fallback: Try matching with payslip company field
        if (!companyData && payslip.company) {
          const normalizedPayslipCompany = payslip.company.trim().toLowerCase();
          companyData = companies.find(c =>
            c.name?.trim().toLowerCase() === normalizedPayslipCompany
          );
          console.log('- Match Strategy 3 (payslip company):', companyData ? `Found: ${companyData.name}` : 'Not found');
        }

        // Final fallback: Use first active company
        if (!companyData) {
          companyData = companies.find(c => c.isActive !== false) || companies[0];
          console.log('- Match Strategy 4 (fallback):', companyData ? `Found: ${companyData.name}` : 'Not found');
        }

        console.log('✅ Final Company Selected:', companyData?.name);
        console.log('🖼️ Company Logo URL:', companyData?.logoUrl || 'No logo');
      } catch (error) {
        console.error('❌ Could not load employee/company data:', error);
      }

      // Colors
      const lightGray = [240, 240, 240];
      const darkGray = [100, 100, 100];
      const primaryBlue = [25, 118, 210];

      let yPos = 15;

      // Add Company Logo at the top (only if company has uploaded one)
      let logoLoaded = false;

      if (companyData?.logoUrl) {
        console.log('🖼️ Attempting to load company logo:', companyData.logoUrl);
        try {
          // Use the download URL directly with jsPDF
          // jsPDF can handle external URLs if they're publicly accessible
          await new Promise((resolve) => {
            const img = new Image();

            // Don't use crossOrigin for Firebase Storage URLs with tokens
            img.onload = () => {
              try {
                // Add logo centered at top
                const logoWidth = 30;
                const logoHeight = 30;
                const logoX = (doc.internal.pageSize.width - logoWidth) / 2;

                // Use the image directly (jsPDF will handle it)
                doc.addImage(img, 'PNG', logoX, yPos, logoWidth, logoHeight);
                logoLoaded = true;
                console.log('✅ Company logo loaded successfully');
                resolve();
              } catch (err) {
                console.log('❌ Could not add logo to PDF:', err);
                resolve();
              }
            };

            img.onerror = (err) => {
              console.log('❌ Could not load logo image, trying alternative method...');

              // Alternative: Use the URL directly in jsPDF (works with public URLs)
              try {
                const logoWidth = 30;
                const logoHeight = 30;
                const logoX = (doc.internal.pageSize.width - logoWidth) / 2;
                doc.addImage(companyData.logoUrl, 'PNG', logoX, yPos, logoWidth, logoHeight);
                logoLoaded = true;
                console.log('✅ Company logo loaded via direct URL');
              } catch (directErr) {
                console.log('❌ Both methods failed');
              }
              resolve();
            };

            // Load without crossOrigin to avoid CORS preflight
            img.src = companyData.logoUrl;
          });
        } catch (error) {
          console.log('❌ Could not load company logo:', error.message);
        }
      }

      // Adjust Y position based on whether logo was loaded
      if (logoLoaded) {
        yPos += 35; // Add space after logo
      } else {
        yPos = 20; // Start from top if no logo
      }

      // Employee Name Header - Large and prominent
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...primaryBlue);
      doc.text(payslip.employeeName.toUpperCase(), 105, yPos, { align: 'center' });
      yPos += 10;

      // Department and Designation Section
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      doc.setFont('helvetica', 'normal');

      const department = employeeData?.department || 'N/A';
      const designation = employeeData?.position || 'N/A';

      doc.text('Department', 20, yPos);
      doc.text('Designation', 120, yPos);
      yPos += 5;
      doc.setFont('helvetica', 'bold');
      doc.text(department, 20, yPos);
      doc.text(designation, 120, yPos);
      yPos += 10;

      // Company Name and Address Section
      doc.setFont('helvetica', 'normal');
      doc.text('Company Name', 20, yPos);
      doc.text('Address', 120, yPos);
      yPos += 5;

      const companyName = employeeData ?
        (employeeData.originalCompanyName || employeeData.company) :
        (companyData?.name || payslip.company || 'Company Name');

      doc.setFont('helvetica', 'bold');
      doc.text(companyName, 20, yPos);

      // Address on right side - with proper wrapping
      let addressLines = [];
      if (companyData?.address) {
        // Build full address string
        let fullAddress = '';
        if (companyData.address.line1) fullAddress += companyData.address.line1;
        if (companyData.address.line2) fullAddress += (fullAddress ? ', ' : '') + companyData.address.line2;
        if (companyData.address.line3) fullAddress += (fullAddress ? ', ' : '') + companyData.address.line3;

        // Add postcode, city, state on new line
        let cityLine = '';
        if (companyData.address.postcode) cityLine += companyData.address.postcode;
        if (companyData.address.city) cityLine += (cityLine ? ' ' : '') + companyData.address.city;
        if (companyData.address.state) cityLine += (cityLine ? ', ' : '') + companyData.address.state;
        if (companyData.address.country && companyData.address.country !== 'Malaysia') {
          cityLine += (cityLine ? ', ' : '') + companyData.address.country;
        }

        // Split long address lines to fit within the right column (max ~70mm width)
        if (fullAddress) {
          const maxWidth = 70; // Maximum width for address column in mm
          const wrappedLines = doc.splitTextToSize(fullAddress, maxWidth);
          addressLines.push(...wrappedLines);
        }

        if (cityLine) {
          const wrappedCityLines = doc.splitTextToSize(cityLine, 70);
          addressLines.push(...wrappedCityLines);
        }
      }

      if (addressLines.length === 0) {
        addressLines = ['2-21, Jalan 8/35, Seksyen 8', '43650 Bandar Baru Bangi', 'Selangor'];
      }

      addressLines.forEach((line, index) => {
        doc.text(line, 120, yPos + (index * 5));
      });

      yPos += Math.max(5, addressLines.length * 5) + 5;

      // Pay Period - on new line after Company Name
      doc.setFont('helvetica', 'normal');
      doc.text('Pay Period', 20, yPos);
      yPos += 5;

      const monthDate = new Date(payslip.month + '-01');
      const startDate = new Date(monthDate.getFullYear(), monthDate.getMonth(), 1);
      const endDate = new Date(monthDate.getFullYear(), monthDate.getMonth() + 1, 0);

      const formatDate = (date) => {
        const day = String(date.getDate()).padStart(2, '0');
        const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
        const month = monthNames[date.getMonth()];
        const year = date.getFullYear();
        return `${day} ${month} ${year}`;
      };

      doc.setFont('helvetica', 'bold');
      doc.text(`${formatDate(startDate)} to ${formatDate(endDate)}`, 20, yPos);
      yPos += 15;

      // CARD 1: Basic Pay and Employee Deductions
      const card1X = 20;
      const card1Width = 80;
      let card1Y = yPos;
      const card1StartY = card1Y;
      const rowHeight = 8;

      doc.setDrawColor(220, 220, 220);
      doc.setLineWidth(0.3);
      doc.setFontSize(9);

      // Basic Pay
      doc.setFillColor(...lightGray);
      doc.rect(card1X, card1Y, card1Width, rowHeight, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.text('BASIC PAY', card1X + 2, card1Y + 5);
      doc.setFont('helvetica', 'normal');
      doc.text('RM ' + (payslip.basicSalary || 0).toFixed(2), card1X + card1Width - 2, card1Y + 5, { align: 'right' });
      card1Y += rowHeight;

      // Employee EPF
      doc.setFillColor(255, 255, 255);
      doc.rect(card1X, card1Y, card1Width, rowHeight, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.text('EMPLOYEE EPF', card1X + 2, card1Y + 5);
      doc.setFont('helvetica', 'normal');
      doc.text('RM ' + (payslip.employeeEPF || 0).toFixed(2), card1X + card1Width - 2, card1Y + 5, { align: 'right' });
      card1Y += rowHeight;

      // Employee EIS
      doc.setFillColor(...lightGray);
      doc.rect(card1X, card1Y, card1Width, rowHeight, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.text('EMPLOYEE EIS', card1X + 2, card1Y + 5);
      doc.setFont('helvetica', 'normal');
      doc.text('RM ' + (payslip.employeeEIS || 0).toFixed(2), card1X + card1Width - 2, card1Y + 5, { align: 'right' });
      card1Y += rowHeight;

      // Employee SOCSO
      doc.setFillColor(255, 255, 255);
      doc.rect(card1X, card1Y, card1Width, rowHeight, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.text('EMPLOYEE SOCSO', card1X + 2, card1Y + 5);
      doc.setFont('helvetica', 'normal');
      doc.text('RM ' + (payslip.employeeSOCSO || 0).toFixed(2), card1X + card1Width - 2, card1Y + 5, { align: 'right' });
      card1Y += rowHeight;

      // Draw Card 1 border
      const card1Height = card1Y - card1StartY;
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.5);
      doc.rect(card1X, card1StartY, card1Width, card1Height);

      // CARD 2: Two-column layout with employer contributions and net wages
      const card2X = 20;
      const card2Width = 170;
      const colWidth = card2Width / 2;
      let card2Y = card1Y + 10; // Add spacing between cards
      const card2StartY = card2Y;

      // Row 1: Gross Wages | Employer EPF
      doc.setFillColor(...lightGray);
      doc.rect(card2X, card2Y, colWidth, rowHeight, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 0, 0);
      doc.text('Gross Wages', card2X + 2, card2Y + 5);
      doc.setFont('helvetica', 'normal');
      doc.text('RM ' + (payslip.grossSalary || 0).toFixed(2), card2X + colWidth - 2, card2Y + 5, { align: 'right' });

      doc.setFillColor(255, 255, 255);
      doc.rect(card2X + colWidth, card2Y, colWidth, rowHeight, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.text('Employer EPF', card2X + colWidth + 2, card2Y + 5);
      doc.setFont('helvetica', 'normal');
      doc.text('RM ' + (payslip.employerEPF || 0).toFixed(2), card2X + card2Width - 2, card2Y + 5, { align: 'right' });
      card2Y += rowHeight;

      // Row 2: Employer EIS | Employer SOCSO
      doc.setFillColor(255, 255, 255);
      doc.rect(card2X, card2Y, colWidth, rowHeight, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.text('Employer EIS', card2X + 2, card2Y + 5);
      doc.setFont('helvetica', 'normal');
      doc.text('RM ' + (payslip.employerEIS || 0).toFixed(2), card2X + colWidth - 2, card2Y + 5, { align: 'right' });

      doc.setFillColor(...lightGray);
      doc.rect(card2X + colWidth, card2Y, colWidth, rowHeight, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.text('Employer SOCSO', card2X + colWidth + 2, card2Y + 5);
      doc.setFont('helvetica', 'normal');
      doc.text('RM ' + (payslip.employerSOCSO || 0).toFixed(2), card2X + card2Width - 2, card2Y + 5, { align: 'right' });
      card2Y += rowHeight;

      // Row 3: Nett Wages | EMPLOYEE EPF
      doc.setFillColor(...lightGray);
      doc.rect(card2X, card2Y, colWidth, rowHeight, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.text('Nett Wages', card2X + 2, card2Y + 5);
      doc.setFont('helvetica', 'normal');
      doc.text('RM ' + (payslip.netSalary || 0).toFixed(2), card2X + colWidth - 2, card2Y + 5, { align: 'right' });

      doc.setFillColor(255, 255, 255);
      doc.rect(card2X + colWidth, card2Y, colWidth, rowHeight, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.text('EMPLOYEE EPF', card2X + colWidth + 2, card2Y + 5);
      doc.setFont('helvetica', 'normal');
      doc.text('RM ' + (payslip.employeeEPF || 0).toFixed(2), card2X + card2Width - 2, card2Y + 5, { align: 'right' });
      card2Y += rowHeight;

      // Row 4: EMPLOYEE EIS | EMPLOYEE SOCSO
      doc.setFillColor(255, 255, 255);
      doc.rect(card2X, card2Y, colWidth, rowHeight, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.text('EMPLOYEE EIS', card2X + 2, card2Y + 5);
      doc.setFont('helvetica', 'normal');
      doc.text('RM ' + (payslip.employeeEIS || 0).toFixed(2), card2X + colWidth - 2, card2Y + 5, { align: 'right' });

      doc.setFillColor(...lightGray);
      doc.rect(card2X + colWidth, card2Y, colWidth, rowHeight, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.text('EMPLOYEE SOCSO', card2X + colWidth + 2, card2Y + 5);
      doc.setFont('helvetica', 'normal');
      doc.text('RM ' + (payslip.employeeSOCSO || 0).toFixed(2), card2X + card2Width - 2, card2Y + 5, { align: 'right' });
      card2Y += rowHeight;

      // Row 5: Zakat | MTD/PCB
      doc.setFillColor(...lightGray);
      doc.rect(card2X, card2Y, colWidth, rowHeight, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.text('Zakat', card2X + 2, card2Y + 5);
      doc.setFont('helvetica', 'normal');
      doc.text('RM ' + (payslip.zakat || 0).toFixed(2), card2X + colWidth - 2, card2Y + 5, { align: 'right' });

      doc.setFillColor(255, 255, 255);
      doc.rect(card2X + colWidth, card2Y, colWidth, rowHeight, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.text('MTD/PCB', card2X + colWidth + 2, card2Y + 5);
      doc.setFont('helvetica', 'normal');
      doc.text('RM ' + (payslip.mtdPCB || 0).toFixed(2), card2X + card2Width - 2, card2Y + 5, { align: 'right' });
      card2Y += rowHeight;

      // Draw Card 2 border
      const card2Height = card2Y - card2StartY;
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.5);
      doc.rect(card2X, card2StartY, card2Width, card2Height);

      // Vertical line to separate columns in Card 2
      doc.line(card2X + colWidth, card2StartY, card2X + colWidth, card2Y);

      yPos = card2Y;

      yPos += 15;

      // Bank Details Section
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(0, 0, 0);

      // Use payment method from payslip data
      const paymentMethod = payslip.paymentMethod || 'GIRO';
      doc.text('Salary Credited To', 20, yPos);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...primaryBlue);
      doc.text(paymentMethod.toUpperCase(), 70, yPos);
      yPos += 8;

      const accountNumber = employeeData?.accountNumber || 'N/A';
      const bankFullName = employeeData?.bankFullName || employeeData?.bankName || 'N/A';

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(0, 0, 0);
      doc.text('Bank account', 20, yPos);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...primaryBlue);

      // Only show bank details if data exists
      if (accountNumber !== 'N/A' && bankFullName !== 'N/A') {
        doc.text(`${bankFullName.toUpperCase()} - ${accountNumber}`, 70, yPos);
      } else if (bankFullName !== 'N/A') {
        doc.text(bankFullName.toUpperCase(), 70, yPos);
      } else if (accountNumber !== 'N/A') {
        doc.text(accountNumber, 70, yPos);
      } else {
        doc.text('N/A', 70, yPos);
      }
      yPos += 15;

      // Messages Section
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 0, 0);
      doc.text('Messages', 20, yPos);
      yPos += 5;

      // Draw message box
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.3);
      doc.rect(20, yPos, 170, 20);

      // Display message if exists
      if (payslip.message && payslip.message.trim() !== '') {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(0, 0, 0);

        // Split message into lines to fit within the box (max width ~165mm)
        const messageLines = doc.splitTextToSize(payslip.message, 165);
        let messageY = yPos + 5;

        // Display each line (max 3 lines to fit in the box)
        messageLines.slice(0, 3).forEach((line, index) => {
          doc.text(line, 22, messageY);
          messageY += 5;
        });
      }

      yPos += 20;

      // Footer
      doc.setFontSize(8);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(...darkGray);
      doc.text('This is a system generated payslip', 105, 285, { align: 'center' });

      // Save the PDF
      const fileName = `Payslip_${payslip.employeeName.replace(/\s+/g, '_')}_${payslip.month}.pdf`;
      doc.save(fileName);

      return true;
    } catch (error) {
      console.error('Payslip PDF generation failed:', error);
      return false;
    }
  }


  /**
   * Generates standardized filename
   */
  generateFilename(prefix, filters = {}) {
    const today = new Date();
    const dateStr = `${today.getDate().toString().padStart(2, '0')}${(today.getMonth() + 1).toString().padStart(2, '0')}${today.getFullYear()}`;
    return `${prefix}_${dateStr}.pdf`;
  }
}

export const pdfService = new PDFService();
export default pdfService;